## Load libraries, example data, and .py file

In [1]:
#load libraries
import pandas as pd
import numpy as np
import sys

#load example data
example_responses = pd.read_csv("../../raw/example_responses.csv", float_precision='round_trip')

#load .py file
sys.path.append('../../progs/')
import bain_response_enrich as bre

## Run example

### a. input

In [6]:
example_responses.head()

,UID,I always choose higher end hotels,On vacation I pride myself on discovering new places and things my friends have not seen before,I choose more expensive hotels and accommodations to make sure I get the best service and amenities,It is important for me to be in a luxurious setting and to be pampered on vacation,I like to immerse myself in the local culture when on vacation,The difference between luxury and standard hotels just is not big enough to justify the cost,I always pay more for a higher class of room on my vacations,I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation,I think spending more for unique experiences is part of what makes a vacation special,I like to go on vacations that are off the beaten path,Assigned Segment,Assigned Segment (Model Value),Cheap + Comfy,Cheap + Curious,Curious,Comfy,Craver,Caviar
0,1,5,5,5,2,4,5,1,5,3,4,Curious,85.243,77.934,77.149,85.243,82.365,83.982,78.588
1,2,1,5,2,1,5,5,2,4,4,5,Cheap + Curious,69.330,61.845,69.330,62.894,54.453,47.986,42.628
2,3,3,5,3,3,5,3,3,5,5,5,Curious,85.859,76.047,80.723,85.859,80.084,83.421,77.704
3,4,3,3,3,3,3,3,3,3,3,3,Comfy,50.574,46.947,39.945,47.759,50.574,43.925,45.594
4,5,5,5,5,5,5,5,5,5,5,5,Craver,137.509,106.069,105.879,123.931,122.318,137.509,128.542

### b. output

In [7]:
bre.bain_response_enrich(example_responses)

,UID,I always choose higher end hotels,On vacation I pride myself on discovering new places and things my friends have not seen before,I choose more expensive hotels and accommodations to make sure I get the best service and amenities,It is important for me to be in a luxurious setting and to be pampered on vacation,I like to immerse myself in the local culture when on vacation,The difference between luxury and standard hotels just is not big enough to justify the cost,I always pay more for a higher class of room on my vacations,I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation,I think spending more for unique experiences is part of what makes a vacation special,I like to go on vacations that are off the beaten path,Assigned Segment,Assigned Segment (Model Value),Cheap + Comfy,Cheap + Curious,Curious,Comfy,Craver,Caviar
0,1,5,5,5,2,4,5,1,5,3,4,Curious,85.243,77.934,77.149,85.243,82.365,83.982,78.588
1,2,1,5,2,1,5,5,2,4,4,5,Cheap + Curious,69.330,61.845,69.330,62.894,54.453,47.986,42.628
2,3,3,5,3,3,5,3,3,5,5,5,Curious,85.859,76.047,80.723,85.859,80.084,83.421,77.704
3,4,3,3,3,3,3,3,3,3,3,3,Comfy,50.574,46.947,39.945,47.759,50.574,43.925,45.594
4,5,5,5,5,5,5,5,5,5,5,5,Craver,137.509,106.069,105.879,123.931,122.318,137.509,128.542
5,6,5,2,5,5,2,1,5,1,5,3,Caviar,82.615,54.519,39.458,65.020,73.761,75.895,82.615